name: "Print Shopping List"
description: API Service to Print Alexa Shopping List
version: 1.0.3
slug: print-shopping-list
url: https://github.com/mastria/hassio-addons/tree/main/print-shopping-list
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  8000/tcp: 8000
options:
  printer_ip: ""
  log_level: info
schema:
  printer_ip: str?
  log_level: list(emergency|alert|critical|error|warning|notice|info|debug)
startup: application
init: false
