build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:17.2.3
  amd64: ghcr.io/hassio-addons/base/amd64:17.2.3
  armhf: ghcr.io/hassio-addons/base/armhf:17.2.3
  armv7: ghcr.io/hassio-addons/base/armv7:17.2.3
  i386: ghcr.io/hassio-addons/base/i386:17.2.3
labels:
  org.opencontainers.image.title: "Intelbras Solar"
  org.opencontainers.image.description: "Integração com o painel da Intelbras Solar."
  org.opencontainers.image.source: "https://github.com/mastria/hassio-addons/tree/main/intelbras-solar"
  org.opencontainers.image.licenses: "MIT"
codenotary:
  signer: codenotary@frenck.dev
