build_from:
  amd64: ghcr.io/hassio-addons/debian-base/amd64:9.1.0
  aarch64: ghcr.io/hassio-addons/debian-base/aarch64:9.1.0
labels:
  org.opencontainers.image.title: "CUPS AirPrint"
  org.opencontainers.image.description: "A CUPS print server with working AirPrint."
  org.opencontainers.image.source: "https://github.com/mastria/hassio-addons/tree/main/cups-airprint"
  org.opencontainers.image.licenses: "MIT"