build_from:
  amd64: ghcr.io/hassio-addons/debian-base:7.8.3
  aarch64: ghcr.io/hassio-addons/debian-base:7.8.3
  armv7: ghcr.io/hassio-addons/debian-base:7.8.3
  armhf: ghcr.io/hassio-addons/debian-base:7.8.3
  i386: ghcr.io/hassio-addons/debian-base:7.8.3
labels:
  org.opencontainers.image.title: "CUPS AirPrint"
  org.opencontainers.image.description: "A CUPS print server with working AirPrint."
  org.opencontainers.image.source: "https://github.com/mastria/hassio-addons/tree/main/cups-airprint"
  org.opencontainers.image.licenses: "MIT"